### PR TITLE
Prepare for future stdlib

### PR DESCRIPTION
**Pull request by UnixJunkie**

### CODE REVIEW

**Comment by gasche** [comment]
When I suggested that you implement the new operations, I had not really looked at the implementation. I see now that this datastructure implements Patricia Tree that seem to be unsorted (this is what I assume from the `List.sort` call in `elements`).

Assuming that no sorting invariant is maintained on this data-structure, then I do not think that it is a good idea to pretend that you can expose the same interface as `Set.S`. The latter is tailed to ordered representations; in particular, users of the interface implicitly assumes that `min_elt` or  `find_first` are somewhat efficient operations, without requiring linear-time computation in all cases. You may be better served by, instead, defining an interface that is actually adapted to the data structure that you expose.

This is not a criticism of your implementation choices, but more of a general design choice for where you want the library to go. Note that a choice was already made in the direction that you are currently taking (of implementing the ordered interface no matter what), by defining `{max,min}_elt` and ensuring that `elements` respects an ordering invariant. But now you are sliding downward on the performance-mismatch slope, taking up speed.

(Another option would be to have *ordered* Patricia Sets/Maps, I suppose. Then you could have an implementation of the ordered interface that is natural.)

**Comment by UnixJunkie** [comment]
@backtracking will have the last word. But in my experience, the whole purpose of ptset is to be
a drop-in replacement to the stdlib's set interface when you manipulate integer sets.

**Comment by backtracking** [comment]
It can be seen indeed as a replacement for Set, sometimes, because Patricia trees offer unicity of representation (so that you can use OCaml's structural equality on sets) and a slightly more efficient union operation (though in practice it is hard to observe a significant difference wrt Set).

Little-endian Patricia trees indeed do not provide any simple way of traversing elements in sorted order, so it is hard to comply to Set's interface and I have to agree with Gabriel's remark. I like the suggestion of dropping "include Set.S" in Ptset.mli in favor of a customed (and smaller) interface.

Big-endian Patricia trees, on the contrary, do provide an efficient way of traversing elements in sorted order (may be with some careful check regarding the way the sign bit is handled). I guess it could match Set.S interface with some effort.

**Comment by UnixJunkie** [comment]
I will not send more code, so please take what you like / drop what you don't like.

**Comment by backtracking** [comment]
I took some of the _opt functions (but not all, since elements is no more part of the implementation).

**Pull request closed without merging**
